[[pages]]
name = "Overview"
icon = "🏠"
is_section = true

[[pages]]
path = "app_pages/ftm.py"
name = "Feed the Monster"
icon = "👾"

[[pages]]
path = "app_pages/assessments.py"
name = "Assessment Summary Data"
icon = "📋"

[[pages]]
path = "app_pages/comparison.py"
name = "Assessment × FTM"
icon = "🔀"


